/*! OTPAuth v2.0.0 | (c) Héctor Molinero Fernández <hector@molinero.xyz> | https://github.com/zant95/otpauth | MIT */
(function(){'use strict';var L={scope:{},getGlobal:function(l){return"undefined"!=typeof window&&window===l?l:"undefined"!=typeof global&&null!=global?global:l}};L.global=L.getGlobal(this);
function T(){return function(l){function g(e){if(h[e])return h[e].exports;var c=h[e]={i:e,l:!1,exports:{}};l[e].call(c.exports,c,c.exports,g);c.l=!0;return c.exports}var h={};g.m=l;g.c=h;g.i=function(e){return e};g.d=function(e,c,a){g.o(e,c)||Object.defineProperty(e,c,{configurable:!1,enumerable:!0,get:a})};g.n=function(e){var c=e&&e.__esModule?function(){return e["default"]}:function(){return e};g.d(c,"a",c);return c};g.o=function(e,c){return Object.prototype.hasOwnProperty.call(e,c)};g.p="";return g(g.s=
7)}([function(l,g){var h={uint:{},raw:{},b32:{},hex:{}};g.a=h;h.uint.decode=function(e){e=new Uint8Array(e);for(var c=0,a=0;a<e.length;a++)0!==e[a]&&(c*=256,c+=e[a]);return c};h.uint.encode=function(e){for(var c=new ArrayBuffer(8),a=new Uint8Array(c),b=7;0<=b&&0!==e;b--)a[b]=e&255,e-=a[b],e/=256;return c};h.raw.decode=function(e){e=new Uint8Array(e);for(var c="",a=0;a<e.length;a++)c+=String.fromCharCode(e[a]);return c};h.raw.encode=function(e){for(var c=new ArrayBuffer(e.length),a=new Uint8Array(c),
b=0;b<e.length;b++)a[b]=e.charCodeAt(b);return c};h.b32.alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";h.b32.decode=function(e){e=new Uint8Array(e);for(var c=0,a=0,b="",d=0;d<e.length;d++)for(a=a<<8|e[d],c+=8;5<=c;)b+=h.b32.alphabet[a>>>c-5&31],c-=5;0<c&&(b+=h.b32.alphabet[a<<5-c&31]);return b};h.b32.encode=function(e){var c=e.toUpperCase();e=new ArrayBuffer(5*e.length/8|0);for(var a=new Uint8Array(e),b=0,d=0,f=0,m=0;m<c.length;m++){var M=h.b32.alphabet.indexOf(c[m]);if(-1===M)throw Error("Invalid character found: "+
c[m]);d=d<<5|M;b+=5;8<=b&&(a[f++]=d>>>b-8&255,b-=8)}return e};h.hex.decode=function(e){e=new Uint8Array(e);for(var c="",a=0;a<e.length;a++)var b=e[a].toString(16),c=c+(1===b.length?"0"+b:b);return c.toUpperCase()};h.hex.encode=function(e){for(var c=new ArrayBuffer(e.length/2),a=new Uint8Array(c),b=0;b<a.length;b++)a[b]=parseInt(e.substr(2*b,2),16);return c}},function(l,g,h){function e(b){var d=void 0===b?{}:b;b=d.buffer;d=void 0===d.size?20:d.size;this.buffer="undefined"===typeof b?this.buffer=a.a.randomBytes(d).buffer:
b}var c=h(0),a=h(4);L.global.Object.defineProperties(e.prototype,{raw:{configurable:!0,enumerable:!0,get:function(){Object.defineProperty(this,"raw",{enumerable:!0,configurable:!0,writable:!0,value:c.a.raw.decode(this.buffer)});return this.raw}},b32:{configurable:!0,enumerable:!0,get:function(){Object.defineProperty(this,"b32",{enumerable:!0,configurable:!0,writable:!0,value:c.a.b32.decode(this.buffer)});return this.b32}},hex:{configurable:!0,enumerable:!0,get:function(){Object.defineProperty(this,
"hex",{enumerable:!0,configurable:!0,writable:!0,value:c.a.hex.decode(this.buffer)});return this.hex}}});g.a=e},function(l,g,h){function e(a){var b=void 0===a?{}:a;a=void 0===b.issuer?"":b.issuer;var m=void 0===b.label?"OTPAuth":b.label,f=void 0===b.secret?new d.a:b.secret,c=void 0===b.algorithm?"SHA1":b.algorithm,e=void 0===b.digits?6:b.digits,b=void 0===b.period?30:b.period;this.issuer=a;this.label=m;this.secret=f;this.algorithm=c;this.digits=e;this.period=b}function c(a){var b=void 0===a?{}:a;
a=void 0===b.issuer?"":b.issuer;var m=void 0===b.label?"OTPAuth":b.label,f=void 0===b.secret?new d.a:b.secret,c=void 0===b.algorithm?"SHA1":b.algorithm,e=void 0===b.digits?6:b.digits,b=void 0===b.counter?0:b.counter;this.issuer=a;this.label=m;this.algorithm=c;this.secret=f;this.digits=e;this.counter=b}var a=h(0),b=h(4),d=h(1),f=h(3);c.generate=function(d){var f=void 0===d.digits?6:d.digits,m=void 0===d.pad?!0:d.pad;d=new Uint8Array(b.a.hmacDigest(void 0===d.algorithm?"SHA1":d.algorithm,d.secret.buffer,
a.a.uint.encode(void 0===d.counter?0:d.counter)));var c=d[d.byteLength-1]&15;d=((d[c]&127)<<24|(d[c+1]&255)<<16|(d[c+2]&255)<<8|d[c+3]&255)%Math.pow(10,f);return m?Array(1+f-String(d).length).join("0")+d:d};c.prototype.generate=function(a){a=void 0===a?{}:a;var b=void 0===a.counter?this.counter++:a.counter;return c.generate({secret:this.secret,algorithm:this.algorithm,digits:this.digits,counter:b,pad:a.pad})};c.validate=function(a){var b=a.token,d=a.secret,f=a.algorithm,m=void 0===a.counter?0:a.counter;
a=void 0===a.window?50:a.window;for(var e=parseInt(b,10),h=m-a;h<=m+a;++h){var g=c.generate({secret:d,algorithm:f,counter:h,digits:b.length,pad:!1});if(e===g)return h-m}return null};c.prototype.validate=function(a){return c.validate({token:a.token,secret:this.secret,algorithm:this.algorithm,counter:void 0===a.counter?this.counter:a.counter,window:a.window})};c.prototype.toString=function(){return f.a.stringify(this)};g.a=c;e.generate=function(a){var b=a.secret,d=a.algorithm,f=a.digits,m=void 0===
a.period?30:a.period,e=void 0===a.timestamp?Date.now():a.timestamp;return c.generate({secret:b,algorithm:d,digits:f,counter:Math.floor(e/1E3/m),pad:a.pad})};e.prototype.generate=function(a){a=void 0===a?{}:a;var b=void 0===a.timestamp?Date.now():a.timestamp;return e.generate({secret:this.secret,algorithm:this.algorithm,digits:this.digits,period:this.period,timestamp:b,pad:a.pad})};e.validate=function(a){var b=a.token,d=a.secret,f=a.algorithm,m=void 0===a.period?30:a.period,e=void 0===a.timestamp?
Date.now():a.timestamp;return c.validate({token:b,secret:d,algorithm:f,counter:Math.floor(e/1E3/m),window:a.window})};e.prototype.validate=function(a){return e.validate({token:a.token,secret:this.secret,algorithm:this.algorithm,period:this.period,timestamp:a.timestamp,window:a.window})};e.prototype.toString=function(){return f.a.stringify(this)};g.b=e},function(l,g,h){function e(){}var c=h(0),a=h(1),b=h(2),d=/^otpauth:\/\/([ht]otp)\/(.+)\?((?:&?(?:issuer|label|secret|algorithm|digits|counter|period)=[^&]+)+)$/i,
f=/^[2-7A-Z]+$/i,m=/SHA(?:1|256|512)/i,M=/^[+-]?[0-9]+$/,Y=/^\+?[1-9][0-9]*$/;e.parse=function(e){var k=decodeURIComponent(e).match(d);if(null===k)throw Error("Invalid URI format");var h=k[1].toLowerCase();e=k[2].split(/:(.+)/,2);var k=k[3].split("\x26").reduce(function(a,b){b=b.split(/=(.+)/,2);var d=b[0].toLowerCase();a[d]=b[1];return a},{}),g={};if("hotp"===h)if(h=b.a,"undefined"!==typeof k.counter&&M.test(k.counter))g.counter=parseInt(k.counter,10);else throw Error("Missing or invalid 'counter' parameter");
else if("totp"===h){if(h=b.b,"undefined"!==typeof k.period)if(Y.test(k.period))g.period=parseInt(k.period,10);else throw Error("Invalid 'period' parameter");}else throw Error("Unknown OTP type");if(2===e.length)if(g.label=e[1],"undefined"===typeof k.issuer)g.issuer=e[0];else if(k.issuer===e[0])g.issuer=k.issuer;else throw Error("Invalid 'issuer' parameter");else g.label=e[0],"undefined"!==typeof k.issuer&&(g.issuer=k.issuer);if("undefined"!==typeof k.secret&&f.test(k.secret))g.secret=new a.a({buffer:c.a.b32.encode(k.secret)});
else throw Error("Missing or invalid 'secret' parameter");if("undefined"!==typeof k.algorithm)if(m.test(k.algorithm))g.algorithm=k.algorithm;else throw Error("Invalid 'algorithm' parameter");if("undefined"!==typeof k.digits)if(Y.test(k.digits))g.digits=parseInt(k.digits,10);else throw Error("Invalid 'digits' parameter");return new h(g)};e.stringify=function(a){if(!(a instanceof b.a||a instanceof b.b))throw Error("Invalid 'HOTP/TOTP' object");return encodeURI("otpauth://"+(a instanceof b.b?"totp":
"hotp")+(0<a.issuer.length?"/"+a.issuer+":"+a.label+"?issuer\x3d"+a.issuer+"\x26":"/"+a.label+"?")+("secret\x3d"+a.secret.b32)+("\x26algorithm\x3d"+a.algorithm)+("\x26digits\x3d"+a.digits)+(a instanceof b.b?"\x26period\x3d"+a.period:"\x26counter\x3d"+a.counter))};g.a=e},function(l,g,h){(function(e){var c=h(6),a=h.n(c),c={};g.a=c;var b;"undefined"===typeof window&&"undefined"!==typeof l&&"undefined"!==typeof l.exports&&(b=eval("require")("crypto"));if("undefined"!==typeof b){var d;d="function"===typeof Buffer.from?
Buffer.from:function(a){var b=new Buffer(a.byteLength);a=new Uint8Array(a);for(var d=0;d<a.length;d++)b[d]=a[d];return b};var f;f=Buffer.prototype instanceof Uint8Array?function(a){return a}:function(a){for(var b=new Uint8Array(a.length),d=0;d<b.length;d++)b[d]=a[d];return b};c.randomBytes=function(a){return f(b.randomBytes(a))};c.hmacDigest=function(a,c,e){return f(b.createHmac(a,d(c)).update(d(e)).digest())}}else{var m;"undefined"!==typeof e.crypto&&"function"===typeof e.crypto.getRandomValues?
m=function(a){e.crypto.getRandomValues(a)}:"undefined"!==typeof e.msCrypto&&"function"===typeof e.msCrypto.getRandomValues?m=function(a){e.msCrypto.getRandomValues(a)}:(console.warn("Cryptography API not available, falling back to 'Math.random'..."),m=function(a){for(var b=0;b<a.length;b++)a[b]=Math.floor(256*Math.random())});c.randomBytes=function(a){a=new Uint8Array(a);m(a);return a};c.hmacDigest=function(b,d,f){b=a.a.hash[b.toLowerCase()];if("undefined"===typeof b)throw Error("Unknown hash function");
d=new a.a.misc.hmac(a.a.codec.arrayBuffer.toBits(d),b);d.update(a.a.codec.arrayBuffer.toBits(f));return a.a.codec.arrayBuffer.fromBits(d.digest(),!1)}}}).call(g,h(5))},function(l){var g;g=function(){return this}();try{g=g||Function("return this")()||(0,eval)("this")}catch(h){"object"===typeof window&&(g=window)}l.exports=g},function(l,g){var h,e,c={cipher:{},hash:{},keyexchange:{},mode:{},misc:{},codec:{},exception:{corrupt:function(a){this.toString=function(){return"CORRUPT: "+this.message};this.message=
a},invalid:function(a){this.toString=function(){return"INVALID: "+this.message};this.message=a},bug:function(a){this.toString=function(){return"BUG: "+this.message};this.message=a},notReady:function(a){this.toString=function(){return"NOT READY: "+this.message};this.message=a}},bitArray:{bitSlice:function(a,b,d){a=c.bitArray._shiftRight(a.slice(b/32),32-(b&31)).slice(1);return void 0===d?a:c.bitArray.clamp(a,d-b)},extract:function(a,b,d){var f=Math.floor(-b-d&31);return((b+d-1^b)&-32?a[b/32|0]<<32-
f^a[b/32+1|0]>>>f:a[b/32|0]>>>f)&(1<<d)-1},concat:function(a,b){if(0===a.length||0===b.length)return a.concat(b);var d=a[a.length-1],f=c.bitArray.getPartial(d);return 32===f?a.concat(b):c.bitArray._shiftRight(b,f,d|0,a.slice(0,a.length-1))},bitLength:function(a){var b=a.length;return 0===b?0:32*(b-1)+c.bitArray.getPartial(a[b-1])},clamp:function(a,b){if(32*a.length<b)return a;a=a.slice(0,Math.ceil(b/32));var d=a.length;b&=31;0<d&&b&&(a[d-1]=c.bitArray.partial(b,a[d-1]&2147483648>>b-1,1));return a},
partial:function(a,b,d){return 32===a?b:(d?b|0:b<<32-a)+1099511627776*a},getPartial:function(a){return Math.round(a/1099511627776)||32},equal:function(a,b){if(c.bitArray.bitLength(a)!==c.bitArray.bitLength(b))return!1;var d=0,f;for(f=0;f<a.length;f++)d|=a[f]^b[f];return 0===d},_shiftRight:function(a,b,d,f){var e;for(void 0===f&&(f=[]);32<=b;b-=32)f.push(d),d=0;if(0===b)return f.concat(a);for(e=0;e<a.length;e++)f.push(d|a[e]>>>b),d=a[e]<<32-b;a=c.bitArray.getPartial(a.length?a[a.length-1]:0);f.push(c.bitArray.partial(b+
a&31,32<b+a?d:f.pop(),1));return f},_xor4:function(a,b){return[a[0]^b[0],a[1]^b[1],a[2]^b[2],a[3]^b[3]]},byteswapM:function(a){var b,d;for(b=0;b<a.length;++b)d=a[b],a[b]=d>>>24|d>>>8&65280|(d&65280)<<8|d<<24;return a}}};"undefined"===typeof ArrayBuffer&&function(a){a.ArrayBuffer=function(){};a.DataView=function(){}}(this);c.codec.arrayBuffer={fromBits:function(a,b,d){var f;b=void 0==b?!0:b;d=d||8;if(0===a.length)return new ArrayBuffer(0);f=c.bitArray.bitLength(a)/8;if(0!==c.bitArray.bitLength(a)%
8)throw new c.exception.invalid("Invalid bit size, must be divisble by 8 to fit in an arraybuffer correctly");b&&0!==f%d&&(f+=d-f%d);d=new DataView(new ArrayBuffer(4*a.length));for(b=0;b<a.length;b++)d.setUint32(4*b,a[b]<<32);a=new DataView(new ArrayBuffer(f));if(a.byteLength===d.byteLength)return d.buffer;f=d.byteLength<a.byteLength?d.byteLength:a.byteLength;for(b=0;b<f;b++)a.setUint8(b,d.getUint8(b));return a.buffer},toBits:function(a){var b=[],d,f,e;if(0===a.byteLength)return[];f=new DataView(a);
d=f.byteLength-f.byteLength%4;for(a=0;a<d;a+=4)b.push(f.getUint32(a));if(0!=f.byteLength%4){e=new DataView(new ArrayBuffer(4));a=0;for(var h=f.byteLength%4;a<h;a++)e.setUint8(a+4-h,f.getUint8(d+a));b.push(c.bitArray.partial(f.byteLength%4*8,e.getUint32(0)))}return b},hexDumpBuffer:function(a){a=new DataView(a);for(var b="",d=0;d<a.byteLength;d+=2){0==d%16&&(b+="\n"+d.toString(16)+"\t");var f;f=a.getUint16(d).toString(16);f+="";f=4<=f.length?f:Array(4-f.length+1).join("0")+f;b+=f+" "}console.log(b.toUpperCase())}};
c.hash.sha1=function(a){a?(this._h=a._h.slice(0),this._buffer=a._buffer.slice(0),this._length=a._length):this.reset()};c.hash.sha1.hash=function(a){return(new c.hash.sha1).update(a).finalize()};c.hash.sha1.prototype={blockSize:512,reset:function(){this._h=this._init.slice(0);this._buffer=[];this._length=0;return this},update:function(a){"string"===typeof a&&(a=c.codec.utf8String.toBits(a));var b,d=this._buffer=c.bitArray.concat(this._buffer,a);b=this._length;a=this._length=b+c.bitArray.bitLength(a);
if(9007199254740991<a)throw new c.exception.invalid("Cannot hash more than 2^53 - 1 bits");if("undefined"!==typeof Uint32Array){var f=new Uint32Array(d),e=0;for(b=this.blockSize+b-(this.blockSize+b&this.blockSize-1);b<=a;b+=this.blockSize)this._block(f.subarray(16*e,16*(e+1))),e+=1;d.splice(0,16*e)}else for(b=this.blockSize+b-(this.blockSize+b&this.blockSize-1);b<=a;b+=this.blockSize)this._block(d.splice(0,16));return this},finalize:function(){var a,b=this._buffer,d=this._h,b=c.bitArray.concat(b,
[c.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);b.push(Math.floor(this._length/4294967296));for(b.push(this._length|0);b.length;)this._block(b.splice(0,16));this.reset();return d},_init:[1732584193,4023233417,2562383102,271733878,3285377520],_key:[1518500249,1859775393,2400959708,3395469782],_f:function(a,b,d,f){if(19>=a)return b&d|~b&f;if(39>=a)return b^d^f;if(59>=a)return b&d|b&f|d&f;if(79>=a)return b^d^f},_S:function(a,b){return b<<a|b>>>32-a},_block:function(a){var b,d,f,c,e,h,
k=this._h,g;if("undefined"!==typeof Uint32Array)for(g=Array(80),b=0;16>b;b++)g[b]=a[b];else g=a;d=k[0];f=k[1];c=k[2];e=k[3];h=k[4];for(a=0;79>=a;a++)16<=a&&(g[a]=this._S(1,g[a-3]^g[a-8]^g[a-14]^g[a-16])),b=this._S(5,d)+this._f(a,f,c,e)+h+g[a]+this._key[Math.floor(a/20)]|0,h=e,e=c,c=this._S(30,f),f=d,d=b;k[0]=k[0]+d|0;k[1]=k[1]+f|0;k[2]=k[2]+c|0;k[3]=k[3]+e|0;k[4]=k[4]+h|0}};c.hash.sha256=function(a){this._key[0]||this._precompute();a?(this._h=a._h.slice(0),this._buffer=a._buffer.slice(0),this._length=
a._length):this.reset()};c.hash.sha256.hash=function(a){return(new c.hash.sha256).update(a).finalize()};c.hash.sha256.prototype={blockSize:512,reset:function(){this._h=this._init.slice(0);this._buffer=[];this._length=0;return this},update:function(a){"string"===typeof a&&(a=c.codec.utf8String.toBits(a));var b,d=this._buffer=c.bitArray.concat(this._buffer,a);b=this._length;a=this._length=b+c.bitArray.bitLength(a);if(9007199254740991<a)throw new c.exception.invalid("Cannot hash more than 2^53 - 1 bits");
if("undefined"!==typeof Uint32Array){var f=new Uint32Array(d),e=0;for(b=512+b-(512+b&511);b<=a;b+=512)this._block(f.subarray(16*e,16*(e+1))),e+=1;d.splice(0,16*e)}else for(b=512+b-(512+b&511);b<=a;b+=512)this._block(d.splice(0,16));return this},finalize:function(){var a,b=this._buffer,d=this._h,b=c.bitArray.concat(b,[c.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);b.push(Math.floor(this._length/4294967296));for(b.push(this._length|0);b.length;)this._block(b.splice(0,16));this.reset();
return d},_init:[],_key:[],_precompute:function(){function a(a){return 4294967296*(a-Math.floor(a))|0}for(var b=0,d=2,f,c;64>b;d++){c=!0;for(f=2;f*f<=d;f++)if(0===d%f){c=!1;break}c&&(8>b&&(this._init[b]=a(Math.pow(d,.5))),this._key[b]=a(Math.pow(d,1/3)),b++)}},_block:function(a){var b,d,f,c=this._h,e=this._key,h=c[0],g=c[1],l=c[2],z=c[3],q=c[4],A=c[5],x=c[6],B=c[7];for(b=0;64>b;b++)16>b?d=a[b]:(d=a[b+1&15],f=a[b+14&15],d=a[b&15]=(d>>>7^d>>>18^d>>>3^d<<25^d<<14)+(f>>>17^f>>>19^f>>>10^f<<15^f<<13)+
a[b&15]+a[b+9&15]|0),d=d+B+(q>>>6^q>>>11^q>>>25^q<<26^q<<21^q<<7)+(x^q&(A^x))+e[b],B=x,x=A,A=q,q=z+d|0,z=l,l=g,g=h,h=d+(g&l^z&(g^l))+(g>>>2^g>>>13^g>>>22^g<<30^g<<19^g<<10)|0;c[0]=c[0]+h|0;c[1]=c[1]+g|0;c[2]=c[2]+l|0;c[3]=c[3]+z|0;c[4]=c[4]+q|0;c[5]=c[5]+A|0;c[6]=c[6]+x|0;c[7]=c[7]+B|0}};c.hash.sha512=function(a){this._key[0]||this._precompute();a?(this._h=a._h.slice(0),this._buffer=a._buffer.slice(0),this._length=a._length):this.reset()};c.hash.sha512.hash=function(a){return(new c.hash.sha512).update(a).finalize()};
c.hash.sha512.prototype={blockSize:1024,reset:function(){this._h=this._init.slice(0);this._buffer=[];this._length=0;return this},update:function(a){"string"===typeof a&&(a=c.codec.utf8String.toBits(a));var b,d=this._buffer=c.bitArray.concat(this._buffer,a);b=this._length;a=this._length=b+c.bitArray.bitLength(a);if(9007199254740991<a)throw new c.exception.invalid("Cannot hash more than 2^53 - 1 bits");if("undefined"!==typeof Uint32Array){var f=new Uint32Array(d),e=0;for(b=1024+b-(1024+b&1023);b<=a;b+=
1024)this._block(f.subarray(32*e,32*(e+1))),e+=1;d.splice(0,32*e)}else for(b=1024+b-(1024+b&1023);b<=a;b+=1024)this._block(d.splice(0,32));return this},finalize:function(){var a,b=this._buffer,d=this._h,b=c.bitArray.concat(b,[c.bitArray.partial(1,1)]);for(a=b.length+4;a&31;a++)b.push(0);b.push(0);b.push(0);b.push(Math.floor(this._length/4294967296));for(b.push(this._length|0);b.length;)this._block(b.splice(0,32));this.reset();return d},_init:[],_initr:[12372232,13281083,9762859,1914609,15106769,4090911,
4308331,8266105],_key:[],_keyr:[2666018,15689165,5061423,9034684,4764984,380953,1658779,7176472,197186,7368638,14987916,16757986,8096111,1480369,13046325,6891156,15813330,5187043,9229749,11312229,2818677,10937475,4324308,1135541,6741931,11809296,16458047,15666916,11046850,698149,229999,945776,13774844,2541862,12856045,9810911,11494366,7844520,15576806,8533307,15795044,4337665,16291729,5553712,15684120,6662416,7413802,12308920,13816008,4303699,9366425,10176680,13195875,4295371,6546291,11712675,15708924,
1519456,15772530,6568428,6495784,8568297,13007125,7492395,2515356,12632583,14740254,7262584,1535930,13146278,16321966,1853211,294276,13051027,13221564,1051980,4080310,6651434,14088940,4675607],_precompute:function(){function a(a){return 4294967296*(a-Math.floor(a))|0}function b(a){return 1099511627776*(a-Math.floor(a))&255}for(var d=0,c=2,e,g;80>d;c++){g=!0;for(e=2;e*e<=c;e++)if(0===c%e){g=!1;break}g&&(8>d&&(this._init[2*d]=a(Math.pow(c,.5)),this._init[2*d+1]=b(Math.pow(c,.5))<<24|this._initr[d]),
this._key[2*d]=a(Math.pow(c,1/3)),this._key[2*d+1]=b(Math.pow(c,1/3))<<24|this._keyr[d],d++)}},_block:function(a){var b,d,c=this._h,e=this._key,g=c[0],h=c[1],k=c[2],l=c[3],z=c[4],q=c[5],A=c[6],x=c[7],B=c[8],N=c[9],Z=c[10],O=c[11],aa=c[12],P=c[13],ba=c[14],Q=c[15],r;if("undefined"!==typeof Uint32Array){r=Array(160);for(var p=0;32>p;p++)r[p]=a[p]}else r=a;var p=g,t=h,E=k,C=l,F=z,D=q,U=A,G=x,v=B,u=N,R=Z,H=O,S=aa,I=P,V=ba,J=Q;for(a=0;80>a;a++){if(16>a)b=r[2*a],d=r[2*a+1];else{d=r[2*(a-15)];var n=r[2*
(a-15)+1];b=(n<<31|d>>>1)^(n<<24|d>>>8)^d>>>7;var w=(d<<31|n>>>1)^(d<<24|n>>>8)^(d<<25|n>>>7);d=r[2*(a-2)];var y=r[2*(a-2)+1],n=(y<<13|d>>>19)^(d<<3|y>>>29)^d>>>6,y=(d<<13|y>>>19)^(y<<3|d>>>29)^(d<<26|y>>>6),W=r[2*(a-7)],X=r[2*(a-16)],K=r[2*(a-16)+1];d=w+r[2*(a-7)+1];b=b+W+(d>>>0<w>>>0?1:0);d+=y;b+=n+(d>>>0<y>>>0?1:0);d+=K;b+=X+(d>>>0<K>>>0?1:0)}r[2*a]=b|=0;r[2*a+1]=d|=0;var W=v&R^~v&S,ca=u&H^~u&I,y=p&E^p&F^E&F,ea=t&C^t&D^C&D,X=(t<<4|p>>>28)^(p<<30|t>>>2)^(p<<25|t>>>7),K=(p<<4|t>>>28)^(t<<30|p>>>
2)^(t<<25|p>>>7),fa=e[2*a],da=e[2*a+1],n=J+((v<<18|u>>>14)^(v<<14|u>>>18)^(u<<23|v>>>9)),w=V+((u<<18|v>>>14)^(u<<14|v>>>18)^(v<<23|u>>>9))+(n>>>0<J>>>0?1:0),n=n+ca,w=w+(W+(n>>>0<ca>>>0?1:0)),n=n+da,w=w+(fa+(n>>>0<da>>>0?1:0)),n=n+d|0,w=w+(b+(n>>>0<d>>>0?1:0));d=K+ea;b=X+y+(d>>>0<K>>>0?1:0);V=S;J=I;S=R;I=H;R=v;H=u;u=G+n|0;v=U+w+(u>>>0<G>>>0?1:0)|0;U=F;G=D;F=E;D=C;E=p;C=t;t=n+d|0;p=w+b+(t>>>0<n>>>0?1:0)|0}h=c[1]=h+t|0;c[0]=g+p+(h>>>0<t>>>0?1:0)|0;l=c[3]=l+C|0;c[2]=k+E+(l>>>0<C>>>0?1:0)|0;q=c[5]=q+D|
0;c[4]=z+F+(q>>>0<D>>>0?1:0)|0;x=c[7]=x+G|0;c[6]=A+U+(x>>>0<G>>>0?1:0)|0;N=c[9]=N+u|0;c[8]=B+v+(N>>>0<u>>>0?1:0)|0;O=c[11]=O+H|0;c[10]=Z+R+(O>>>0<H>>>0?1:0)|0;P=c[13]=P+I|0;c[12]=aa+S+(P>>>0<I>>>0?1:0)|0;Q=c[15]=Q+J|0;c[14]=ba+V+(Q>>>0<J>>>0?1:0)|0}};c.misc.hmac=function(a,b){this._hash=b=b||c.hash.sha256;var d=[[],[]],e,g=b.prototype.blockSize/32;this._baseHash=[new b,new b];a.length>g&&(a=b.hash(a));for(e=0;e<g;e++)d[0][e]=a[e]^909522486,d[1][e]=a[e]^1549556828;this._baseHash[0].update(d[0]);this._baseHash[1].update(d[1]);
this._resultHash=new b(this._baseHash[0])};c.misc.hmac.prototype.encrypt=c.misc.hmac.prototype.mac=function(a){if(this._updated)throw new c.exception.invalid("encrypt on already updated hmac called!");this.update(a);return this.digest(a)};c.misc.hmac.prototype.reset=function(){this._resultHash=new this._hash(this._baseHash[0]);this._updated=!1};c.misc.hmac.prototype.update=function(a){this._updated=!0;this._resultHash.update(a)};c.misc.hmac.prototype.digest=function(){var a=this._resultHash.finalize(),
a=(new this._hash(this._baseHash[1])).update(a).finalize();this.reset();return a};"undefined"!==typeof l&&l.exports&&(l.exports=c);!(h=[],e=function(){return c}.apply(g,h),void 0!==e&&(l.exports=e))},function(l,g,h){var e=h(2);Object.defineProperty(g,"__esModule",{value:!0});var c=h(3),a=h(1);h=h(0);e={HOTP:e.a,TOTP:e.b,URI:c.a,Secret:a.a,Utils:h.a};g["default"]=e;l.exports=e}])}
"object"===typeof exports&&"object"===typeof module?module.exports=T():"function"===typeof define&&define.amd?define([],T):"object"===typeof exports?exports.OTPAuth=T():this.OTPAuth=T();}).call(this);
//# sourceMappingURL=otpauth.js.map